GitHub Actions workflow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -60,9 +60,9 @@ jobs:
       - name: Install dependencies
         run: npm install --legacy-peer-deps
 
-      - name: Run tests with coverage (ignorer erreurs)
+      - name: Run tests with coverage (ignore errors)
         run: |
-          npm run test -- --watch=false --code-coverage || echo "Tests échoués mais on continue..."
+          npm run test -- --watch=false --code-coverage || echo "Tests failed but continuing..."
 
   sonar:
     name: SonarCloud Analysis
@@ -101,10 +101,11 @@ jobs:
         uses: docker/setup-buildx-action@v3
 
       - name: Log in to Nexus Docker Registry
-        run: echo "${{ secrets.NEXUS_PASSWORD }}" | docker login 296a-197-15-124-194.ngrok-free.app -u ${{ secrets.NEXUS_USERNAME }} --password-stdin
+        # **Remplace ici l'URL par ta dernière URL ngrok pour le registre Docker Nexus**
+        run: echo "${{ secrets.NEXUS_PASSWORD }}" | docker login https://a81d-197-15-124-194.ngrok-free.app -u ${{ secrets.NEXUS_USERNAME }} --password-stdin
 
       - name: Build Docker image
-        run: docker build -t 296a-197-15-124-194.ngrok-free.app/frontapp:latest .
+        run: docker build -t a81d-197-15-124-194.ngrok-free.app/frontapp:latest .
 
       - name: Push Docker image
-        run: docker push 296a-197-15-124-194.ngrok-free.app/frontapp:latest
+        run: docker push a81d-197-15-124-194.ngrok-free.app/frontapp:latest
